---

- name: setup cloudera repo
  copy: src=etc/yum.repos.d/cloudera.repo
        dest=/etc/yum.repos.d/cloudera.repo
        mode=0444 owner=root group=root

- name: install zookeeper and jdk8
  yum: name={{ item }} state=present
  with_items: 
    - java-1.8.0-openjdk-headless
    - zookeeper-server

- name: initialize zookeeper
  command: service zookeeper-server init
           creates=/var/lib/zookeeper/version-2/

- name: start zookeeper
  service: name=zookeeper-server state=started enabled=yes
