---

- name: setup cloudera repo
  copy: src=etc/yum.repos.d/cloudera.repo
        dest=/etc/yum.repos.d/cloudera.repo
        mode=0444 owner=root group=root

- name: install zookeeper
  yum: name=zookeeper-server state=present

- name: start zookeeper
  service: name=zookeeper-server state=started enabled=yes
